export const FETCH_TASK = "FETCH_TASK";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAILED = "FETCH_TASK_FAILED";

export const FILTER_TASK = "FILTER_TASK";
export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
